In [9]:
from config import *

In [2]:
import json

In [3]:
import os
import sys

In [4]:
root20 = r"Y:\hwang_Pro\data\2020_tanashi_broccoli\13_roi_on_raw"
root21 = r"Y:\hwang_Pro\data\2021_tanashi_broccoli\13_roi_on_raw"

In [5]:
date20 = ["0518_p", "0520_p", "0522_p", "0525_p", "0526_p", "0528_p"]
date21 = ["210512", "210514", "210515", "210519", "210520", "210526"]

In [15]:
verify_list = os.listdir(f"{root20}/verify")
verify_list

['labeled_20200518_106_DJI_0356.json',
 'labeled_20200518_106_DJI_0360.json',
 'labeled_20200518_106_DJI_0361.json',
 'labeled_20200518_3_DJI_0489.json',
 'labeled_20200518_57_DJI_0442.json']

In [34]:
csv_file = pd.DataFrame(columns=["date", "file_name", "relative_path", "status"])
for d in date20:
    p2 = Paths(d)
    json_name = f"{root20}/{p2.project_name}.json"
    date = p2.project_name.split("_")[3]
    with open(json_name, 'r') as f:
        offset_dict = json.load(f)
    for img_name in offset_dict.keys():
        if f"labeled_{date}_{img_name[:-4]}.json" in verify_list:
            status = "verify"
        else:
            status = "blank"
        csv_file.loc[len(csv_file)] = [date, img_name, offset_dict[img_name]["imagePath"], status]

In [35]:
csv_file

,date,file_name,relative_path,status
0,20200518,1_DJI_0487.JPG,./broccoli_tanashi_5_20200518_P4M_10m/1_DJI_04...,blank
1,20200518,1_DJI_0488.JPG,./broccoli_tanashi_5_20200518_P4M_10m/1_DJI_04...,blank
2,20200518,1_DJI_0489.JPG,./broccoli_tanashi_5_20200518_P4M_10m/1_DJI_04...,blank
3,20200518,2_DJI_0488.JPG,./broccoli_tanashi_5_20200518_P4M_10m/2_DJI_04...,blank
4,20200518,2_DJI_0489.JPG,./broccoli_tanashi_5_20200518_P4M_10m/2_DJI_04...,blank
...,...,...,...,...
6043,20200528,335_DJI_0232.JPG,./broccoli_tanashi_5_20200528_P4M_10m_before/3...,blank
6044,20200528,335_DJI_0233.JPG,./broccoli_tanashi_5_20200528_P4M_10m_before/3...,blank
6045,20200528,336_DJI_0230.JPG,./broccoli_tanashi_5_20200528_P4M_10m_before/3...,blank
6046,20200528,336_DJI_0231.JPG,./broccoli_tanashi_5_20200528_P4M_10m_before/3...,blank
6047,20200528,336_DJI_0287.JPG,./broccoli_tanashi_5_20200528_P4M_10m_before/3...,blank

In [36]:
csv_file[csv_file.status=="verify"]

,date,file_name,relative_path,status
6,20200518,3_DJI_0489.JPG,./broccoli_tanashi_5_20200518_P4M_10m/3_DJI_04...,verify
169,20200518,57_DJI_0442.JPG,./broccoli_tanashi_5_20200518_P4M_10m/57_DJI_0...,verify
315,20200518,106_DJI_0356.JPG,./broccoli_tanashi_5_20200518_P4M_10m/106_DJI_...,verify
316,20200518,106_DJI_0360.JPG,./broccoli_tanashi_5_20200518_P4M_10m/106_DJI_...,verify
317,20200518,106_DJI_0361.JPG,./broccoli_tanashi_5_20200518_P4M_10m/106_DJI_...,verify

In [38]:
csv_file.to_csv(f"{root20}\json_index.csv", index=False)

In [10]:
csv_file21 = pd.DataFrame(columns=["date", "file_name", "relative_path", "status"])
for d in date21:
    p2 = Paths(d, year=2021)
    json_name = f"{root21}/{p2.project_name}.json"
    date = p2.project_name.split("_")[3]
    with open(json_name, 'r') as f:
        offset_dict = json.load(f)
    for img_name in offset_dict.keys():
        csv_file21.loc[len(csv_file21)] = [date, img_name, offset_dict[img_name]["imagePath"], "blank"]

In [11]:
csv_file21

,date,file_name,relative_path,status
0,20210512,1_DJI_0329.JPG,./broccoli_tanashi_5_20210512_P4RTK_15m_M/1_DJ...,blank
1,20210512,1_DJI_0361.JPG,./broccoli_tanashi_5_20210512_P4RTK_15m_M/1_DJ...,blank
2,20210512,1_DJI_0362.JPG,./broccoli_tanashi_5_20210512_P4RTK_15m_M/1_DJ...,blank
3,20210512,2_DJI_0330.JPG,./broccoli_tanashi_5_20210512_P4RTK_15m_M/2_DJ...,blank
4,20210512,2_DJI_0360.JPG,./broccoli_tanashi_5_20210512_P4RTK_15m_M/2_DJ...,blank
...,...,...,...,...
3019,20210526,174_DJI_0045.JPG,./broccoli_tanashi_5_20210526_P4RTK_15m_M/174_...,blank
3020,20210526,174_DJI_0046.JPG,./broccoli_tanashi_5_20210526_P4RTK_15m_M/174_...,blank
3021,20210526,175_DJI_0042.JPG,./broccoli_tanashi_5_20210526_P4RTK_15m_M/175_...,blank
3022,20210526,175_DJI_0043.JPG,./broccoli_tanashi_5_20210526_P4RTK_15m_M/175_...,blank
3023,20210526,175_DJI_0045.JPG,./broccoli_tanashi_5_20210526_P4RTK_15m_M/175_...,blank

In [12]:
csv_file21.to_csv(f"{root21}\json_index.csv", index=False)